
max_width = 120
# wrap_comments = true
# comment_width = 80
# format_code_in_doc_comments = true
# doc_comment_code_block_width = 80

tab_spaces = 3

# fn_single_line = true
# enum_discrim_align_threshold = 18
