CREATE TABLE IF NOT EXISTS twag_tags (
   id CHAR(14) UNIQUE NOT NULL PRIMARY KEY,
   target_url TEXT NOT NULL,
   created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
   last_accessed TIMESTAMP WITH TIME ZONE,
   access_count INTEGER DEFAULT 0,
   last_seen_tap_count INTEGER,
);
