min_version = "2024.11.3"

[settings]
npm.bun = true
pipx.uvx = true

[tools]
"rust" = "1.87"
"cargo:sqlx-cli" = { version = "0.8", default-features = false, features = "native-tls,postgres" }
"cargo:cargo-watch" = "latest"

# Pre-commit tooling
# FIXME: Use the direct version of `hk` when the Aqua package is fixed
"java" = "22"
"pkl" = "0.28"
"cargo:hk" = { version = "1.1", postinstall = "hk install" }
"python" = "3.13"

# SQL formatting
"uv" = "latest"
"pipx:sqlfluff" = "latest"

[tasks.watch]
description = "Watches for changes in the source code and runs the server"
env = { RUST_LOG = "trace", RUST_FMT = "pretty" }
run = "cargo watch -w cargo.toml -w src -w templates -x 'run'"

[tasks.db-auth]
description = "Queries Neon for database creds"
outputs = ["../.env"]
run = [
   "echo \"DATABASE_URL='$(neonctl connection-string dev/ec --database-name twag --role-name twag_admin)'\" >> ../.env",
   "chmod 600 ../.env",
]

[tasks.db-setup]
description = "Initializes the database"
depends = ["db-auth"]
sources = ["../.env", "../migrations/*.sql"]
env = { RUST_LOG = "trace" }
run = "cd .. && sqlx database setup"

[tasks.sqlx-prepare]
description = "Cache schema for SQLx typechecking"
depends = ["db-auth"]
sources = ["../.env"]
run = "cargo sqlx prepare"
